### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by wellisrite** [eriknyquist/generate_life_calendar#2]
hi eriknyquist,

just found your repository will it be possible to autofill the black boxs up to present time?

**Comment by wellisrite** [comment]
![Screenshot from 2019-09-03 18-54-12](https://user-images.githubusercontent.com/33211155/64171200-42977700-ce7c-11e9-906d-5babb05498b2.png)

i have made some update as shown above

**Comment by eriknyquist** [comment]
Certainly this would be possible, but currently this script is working fine
the way I want so I don't think I'll be changing it anytime soon.

Feel free to fork it and add your desired features, though.

Thanks,
Erik

**Comment by wellisrite** [comment]
Okay, 
thank you for the permission
