### ISSUE TITLE
Error: out of memory

### ISSUE THREAD

**Issue by tavousi** [eriknyquist/generate_life_calendar#4]
Hi
when run your code, ERROR is:
Error: out of memory

**Comment by eriknyquist-avive** [comment]
@tavousi  what kind of OS are you on (windows, mac OSX, linux...) ?

**Comment by tavousi** [comment]
windows

**Comment by eriknyquist** [comment]
OK. Can you please show me the arguments you are passing to the script, and the output you are getting from the script?

**Comment by tavousi** [comment]
Please look at the screenshot.it is all.
![error](https://user-images.githubusercontent.com/39909042/102348033-856c5800-3fb6-11eb-8954-b4843dc20eb3.png)

**Comment by eriknyquist-avive** [comment]
`generateLifeCalender.py` is this your own script? it has a different name than the script in my repository. If it is different, can you show me the contents?

**Comment by eriknyquist-avive** [comment]
nevermind, I can reproduce the error on my own windows machine. Looks like some problem with pycairo on windows, it works fine on ubuntu.

I will figure out the problem this weekend when I have some time. In the meantime, if you just want to generate a life calendar, the life calendar generator on my website https://www.ekn.io/calendar/ is working fine, since it's running on linux, so you can use that.

**Comment by tavousi** [comment]
I don't change your script. Thanks for your comments.It is another screenshot.
![Screenshot 2020-12-17 01 00 00](https://user-images.githubusercontent.com/39909042/102409039-ab6c1980-4003-11eb-9a87-bce84b960ea5.png)

**Comment by allibell** [comment]
you might try using the old version `pycairo==1.11.1`. even on ubuntu I've had issues with `1.20.1`

**Comment by Peboli** [comment]
To fix this issue on Windows you can install the pycairo module from binaries provided by Christoph Gohlke.
Uninstall actual pycairo module with `pip uninstall pycairo`
Go to this address [https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo)
Download the binary corresponding to your Python version (cp37 -> Python 3.7, cp38 -> Python 3.8, cp39 -> Python 3.9)
Take also care to OS version, 32 bit (suffix win32.whl) or 64 bit (suffix win_amd64.whl)
Install the binary with `pip install pycairo‑1.20.0‑cp37‑cp37m‑win_amd64.whl` for example if Python 3.7 in 64 bit.
That's it
